### ISSUE TITLE
opencv installation not detected

### ISSUE THREAD

**Issue by JuanCab** [astropy/astrowidgets#90]
Attempts to create an `ImageWidget` (from the Widget Example Using Ginga Jupiter notebook) result in the following error:

```
/Users/juan/anaconda3/lib/python3.7/site-packages/astrowidgets/core.py:72: UserWarning: install opencv or set use_opencv=False
  warnings.warn('install opencv or set use_opencv=False')
```

This is despite the fact that I have version 4.1.0 of the opencv python package installed.  I confirmed when the offending line is run from th notebook separately it throws the following error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-4-85398129f892> in <module>
      1 from ginga import trcalc
      2 
----> 3 trcalc.use('opencv')

~/anaconda3/lib/python3.7/site-packages/ginga/trcalc.py in use(pkgname)
     17 
     18     if pkgname == 'opencv':
---> 19         import cv2
     20         cv2_resize = {
     21             'nearest': cv2.INTER_NEAREST,

ImportError: dlopen(/Users/juan/anaconda3/lib/python3.7/site-packages/cv2.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
  Referenced from: /Users/juan/anaconda3/lib/libopencv_freetype.4.1.dylib
  Reason: Incompatible library version: libopencv_freetype.4.1.dylib requires version 24.0.0 or later, but libfreetype.6.dylib provides version 23.0.0
```

This suggest to me the the `opencv` package installed via conda is *NOT* the correct prerequisite.  Is there a way to force astrowidgets to install the proper opencv during pip installation?

**Comment by JuanCab** [comment]
Solution appears to be to upgrade free type library (installed by conda) to version 2.10.0.  Apparently the opencv installation in conda doesn't have this pre-requiste set properly.

**Comment by pllim** [comment]
`opencv` itself isn't a Python library, right? Updating with conda like you did seems like the right way to go. Seems like it is solved on your end. I don't think we should force users to install it, as in the future, Ginga will not be the only backend that `AstroImage` would support. Please close the issue if there is nothing else that needs to be fixed in this regard. Thanks!

**Comment by mwcraig** [comment]
I think there is still an issue here: conda install open can is not requiring the right version of free type. It may be that the best we can do here is clearly document how to get opencv working. 

Let’s keep this open at least until a doc update I’m planning  for later today. 

Will also try to look at the opencv conda package. @JuanCab — can you check where your opencv is coming from: conda list opencv

**Comment by JuanCab** [comment]
The opencv is coming from conda-forge.  I have already posted to their [github issues page](https://github.com/conda-forge/opencv-feedstock/issues/174) about the problem with the bad freetype dependency.

**Comment by JuanCab** [comment]
The opencv is coming from conda-forge.  I have already posted to their [github issues page](https://github.com/conda-forge/opencv-feedstock/issues/174) about the problem with the bad freetype dependency.  In a nutshell, I updated `opencv` to the `conda-forge` version (which was 4.1.0) from the `default` channel version (3.4.2) and it didn't catch that `freetype` needed to be updated as well.

A clearer error message might make sense (at least echo back the error message from the `import cv2` command).

**Comment by mwcraig** [comment]
Nice sleuthing over at https://github.com/conda-forge/opencv-feedstock/issues/174, @JuanCab! I think for now I'll add a note to the documentation about installing opencv. The only reason I'm hesitant to make opencv a hard requirement is that install with pip looks a little painful (there is a package called opencv-python that provides binary wheels but it isn't quite the same as installing opencv from source or from conda-forge).

**Comment by mwcraig** [comment]
@JuanCab  -- can you https://github.com/astropy/astrowidgets/pull/91/files#diff-62c330cd8da31d476bb63b51bb8b1307 take a look at https://github.com/astropy/astrowidgets/pull/91/files#diff-62c330cd8da31d476bb63b51bb8b1307 and let me know if you think it is adequate for now?

**Comment by mwcraig** [comment]
closed by #91
